# --- 1. BOOTSTRAP ---
exec-once = dbus-update-activation-environment --all

# --- 2. AUDIO/VIDEO SERVICES ---
exec-once = rc-service -U pipewire restart
exec-once = rc-service -U pipewire-pulse restart
exec-once = rc-service -U wireplumber restart

# --- 3. WALLPAPER ---
exec-once = awww-daemon
exec-once = awww img /home/chace-berry/Videos/wallpaper_static.png
exec-once = sleep 1 && awww img /home/chace-berry/Videos/wallpaper_1080p.gif
exec-once = /home/chace-berry/.config/hypr/scripts/pause_wp

# --- 4. PORTALS ---
exec-once = killall -9 xdg-desktop-portal-hyprland xdg-desktop-portal-gtk xdg-desktop-portal; sleep 2 && GTK_THEME=catppuccin-mocha-teal-standard+default /usr/lib/xdg-desktop-portal-hyprland
exec-once = sleep 3 && GTK_THEME=catppuccin-mocha-teal-standard+default /usr/lib/xdg-desktop-portal-gtk
exec-once = sleep 5 && GTK_THEME=catppuccin-mocha-teal-standard+default /usr/lib/xdg-desktop-portal
exec-once = sleep 8 && killall -9 xdg-desktop-portal-hyprland xdg-desktop-portal-gtk xdg-desktop-portal
exec-once = sleep 10 && GTK_THEME=catppuccin-mocha-teal-standard+default /usr/lib/xdg-desktop-portal-hyprland
exec-once = sleep 11 && GTK_THEME=catppuccin-mocha-teal-standard+default /usr/lib/xdg-desktop-portal-gtk
exec-once = sleep 13 && GTK_THEME=catppuccin-mocha-teal-standard+default /usr/lib/xdg-desktop-portal

# --- 5. UI ---
exec-once = bash -c "while true; do wl-gammarelay-rs run; sleep 2; done"
exec-once = bash -c "while true; do ags run ~/Documents/Alterion/Alterion-Os/app.ts; sleep 2; done"
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets,pkcs11

# --- 6. APPS ---
exec-once = sleep 3 && kdeconnect-indicator
exec-once = sleep 5 && steam -silent
exec-once = sleep 3 && discord
exec-once = cursor-clip --daemon
